spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver 
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: sujata
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
